In [6]:
import pandas as pd
from sklearn.feature_selection import SequentialFeatureSelector
from sklearn.svm import LinearSVC
import random

In [7]:
df = pd.read_csv("../../Datasets/Crop/WinnipegDataset.txt", low_memory=False)

for column in df.columns[1:]:
    if df[column].dtype != "float64":
        df[column] = df[column].astype("float")

df.head()

,label,f1,f2,f3,f4,f5,f6,f7,f8,f9,...,f165,f166,f167,f168,f169,f170,f171,f172,f173,f174
0,1,-13.559,-21.407,-11.4040,-15.248,-11.923,-15.291,-2.1548,-7.8474,-10.0020,...,0.18519,0.72602,5.3333,6.000000,0.29489,9.77780,2.44440,1.67700,0.20988,0.65422
1,1,-12.802,-20.335,-10.3990,-14.132,-11.096,-14.361,-2.4039,-7.5330,-9.9369,...,0.33333,-0.48751,2.1111,0.098765,0.83333,0.33333,0.33333,0.84869,0.50617,-0.18898
2,1,-12.431,-19.902,-10.0740,-13.598,-10.829,-14.048,-2.3566,-7.4717,-9.8283,...,0.25926,0.25298,2.2222,0.172840,0.68889,0.88889,0.66667,1.27300,0.30864,0.10483
3,1,-12.689,-19.529,-10.0280,-13.350,-11.056,-14.014,-2.6611,-6.8396,-9.5006,...,0.16049,0.43750,4.1111,0.320990,0.83333,0.33333,0.33333,1.14910,0.38272,0.41603
4,1,-12.686,-19.278,-9.8185,-13.108,-10.932,-13.939,-2.8675,-6.5919,-9.4594,...,0.18519,0.35000,4.0000,0.444440,0.68889,0.88889,0.66667,1.58110,0.20988,0.50000

In [8]:
X = df.iloc[random.sample(range(df.shape[0]), int(df.shape[0] * 0.001)), 1:]
y = df.iloc[random.sample(range(df.shape[0]), int(df.shape[0] * 0.001)), :1]

In [9]:
import warnings
warnings.filterwarnings("ignore")

linear_svc = LinearSVC()
forward_selector = SequentialFeatureSelector(
    linear_svc, scoring="accuracy", n_features_to_select=2, direction="forward")
forward_selector.fit(X, y.values.ravel())

selected_features_mask = forward_selector.get_support()
selected_feature_indices = [i for (i, x) in enumerate(selected_features_mask) if x]

print("Before Forward feature selection:", df.shape)
print("After Forward feature selection:", df.iloc[:, selected_feature_indices + [-1]].shape)

df.iloc[:, [0] + selected_feature_indices].head()

Before Forward feature selection: (325834, 175)
After Forward feature selection: (325834, 3)

   label     f113    f121
0      1  0.38202  22.667
1      1  0.47583  18.556
2      1  0.47160  19.000
3      1  0.40594  17.333
4      1  0.33671  16.667